# Generated by Django 5.2.5 on 2025-08-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flawsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="basic_password",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
